/* The following code was generated by JFlex 1.6.0 */

package ar.edu.itba.geb.compiler.java.core;

import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.0
 * from the specification file <tt>/Users/mgualino/Documents/workspace/twister/src/main/java/ar/edu/itba/geb/compiler/jflex/Parser.flex</tt>
 */
public class AnalizadorLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;
  public static final int CHAR = 4;
  public static final int CHARESC = 6;
  public static final int CHAREND = 8;
  public static final int STRING = 10;
  public static final int ESCAPED = 12;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\4\1\7\1\0\1\4\1\6\22\0\1\4\1\37\1\5"+
    "\3\0\1\40\1\3\1\55\1\56\1\46\1\44\1\51\1\45\1\50"+
    "\1\10\1\2\11\2\1\0\1\52\1\42\1\41\1\43\2\0\1\20"+
    "\1\13\1\17\1\25\1\33\1\34\1\32\1\35\1\16\2\1\1\14"+
    "\1\26\1\27\1\24\1\11\1\1\1\31\1\22\1\30\1\12\1\23"+
    "\1\36\3\1\1\57\1\0\1\60\1\0\1\3\1\0\1\20\1\13"+
    "\1\17\1\25\1\33\1\34\1\32\1\35\1\16\2\1\1\14\1\26"+
    "\1\27\1\24\1\11\1\1\1\31\1\22\1\30\1\12\1\23\1\36"+
    "\2\1\1\1\1\53\1\47\1\54\102\0\27\1\1\0\7\1\30\1"+
    "\1\0\10\1\60\0\2\15\115\0\1\21\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\ufe90\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\0\1\4\2\1\1\0"+
    "\2\1\1\0\7\1\1\5\1\0\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\0\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\0\3\1"+
    "\1\0\2\1\1\26\1\0\1\26\2\1\1\0\7\1"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\1\1\0\2\1\2\41\1\1\2\0"+
    "\2\1\1\0\1\1\1\0\1\1\1\0\1\1\1\42"+
    "\1\1\1\0\4\1\1\0\2\1\1\0\1\1\1\43"+
    "\1\0\1\43\1\1\2\44\1\0\1\1\2\45\1\46"+
    "\2\47\1\1\1\0\1\1\1\0\1\1\1\0\2\1"+
    "\2\50\1\0\1\1\1\0\2\1\2\51\2\52\2\0"+
    "\3\1\2\53\1\0\1\1\1\54\2\0\2\1\1\55"+
    "\1\0\1\1\1\56\1\57\1\56\1\57\2\60";

  private static int [] zzUnpackAction() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\304\0\365\0\u0126\0\u0157"+
    "\0\u0188\0\u01b9\0\u01ea\0\u021b\0\u024c\0\u027d\0\u02ae\0\u02df"+
    "\0\u0310\0\u0341\0\u0372\0\u03a3\0\u03d4\0\u0405\0\u0436\0\u0467"+
    "\0\u0498\0\u04c9\0\u04fa\0\u052b\0\223\0\223\0\223\0\223"+
    "\0\223\0\223\0\223\0\223\0\223\0\223\0\u055c\0\u058d"+
    "\0\u05be\0\u05ef\0\u0620\0\u0651\0\u0682\0\u06b3\0\u06e4\0\u0715"+
    "\0\u0746\0\u0777\0\u07a8\0\u07d9\0\u080a\0\u083b\0\u086c\0\u089d"+
    "\0\u08ce\0\u08ff\0\223\0\223\0\223\0\223\0\223\0\223"+
    "\0\223\0\223\0\223\0\223\0\u0930\0\u0961\0\u0992\0\u09c3"+
    "\0\223\0\61\0\u09f4\0\u0a25\0\u0a56\0\u0a87\0\u0ab8\0\u0ae9"+
    "\0\u0b1a\0\u0b4b\0\u0b7c\0\u0bad\0\u0bde\0\61\0\u0c0f\0\u0c40"+
    "\0\u0c71\0\u0ca2\0\u0cd3\0\u0d04\0\u0d35\0\u0d66\0\u0d97\0\u0dc8"+
    "\0\u0df9\0\223\0\u0e2a\0\61\0\u0e5b\0\223\0\61\0\u0e8c"+
    "\0\u0ebd\0\223\0\61\0\61\0\223\0\61\0\u0eee\0\u0f1f"+
    "\0\u0f50\0\u0f81\0\u0fb2\0\u0fe3\0\u1014\0\u1045\0\223\0\61"+
    "\0\u1076\0\u10a7\0\u10d8\0\u1109\0\u113a\0\223\0\61\0\223"+
    "\0\61\0\u116b\0\u119c\0\u11cd\0\u11fe\0\u122f\0\223\0\61"+
    "\0\u1260\0\u1291\0\61\0\u12c2\0\u12f3\0\u1324\0\u1355\0\61"+
    "\0\u1386\0\u13b7\0\223\0\223\0\61\0\61\0\223\0\61";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\2\1\3\1\0\1\4\1\5\2\4\1\6"+
    "\1\7\1\2\1\10\1\2\1\11\1\12\1\13\1\2"+
    "\1\14\1\15\1\16\2\2\1\17\1\20\1\21\1\22"+
    "\2\2\1\23\2\2\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\0\3\2\5\0"+
    "\4\2\1\0\3\2\1\0\15\2\24\0\1\3\137\0"+
    "\5\5\1\46\53\5\10\0\1\47\51\0\3\2\5\0"+
    "\1\2\1\50\2\2\1\0\3\2\1\0\7\2\1\51"+
    "\5\2\23\0\3\2\5\0\4\2\1\0\3\2\1\0"+
    "\2\2\1\52\12\2\51\0\1\53\32\0\3\2\5\0"+
    "\4\2\1\0\3\2\1\0\5\2\1\54\7\2\23\0"+
    "\3\2\5\0\3\2\1\55\1\0\3\2\1\0\15\2"+
    "\37\0\2\56\11\0\1\57\31\0\3\2\5\0\4\2"+
    "\1\56\1\60\2\2\1\0\6\2\1\61\6\2\23\0"+
    "\3\2\5\0\4\2\1\0\3\2\1\0\2\2\1\62"+
    "\12\2\23\0\3\2\5\0\4\2\1\63\1\64\1\2"+
    "\1\65\1\0\15\2\23\0\3\2\5\0\4\2\1\0"+
    "\3\2\1\0\11\2\1\66\3\2\23\0\3\2\5\0"+
    "\4\2\1\0\3\2\1\0\7\2\1\67\3\2\1\70"+
    "\1\2\23\0\3\2\5\0\4\2\1\0\3\2\1\0"+
    "\11\2\1\71\3\2\23\0\3\2\5\0\4\2\1\0"+
    "\2\2\1\72\1\0\15\2\63\0\1\73\57\0\1\74"+
    "\61\0\1\75\60\0\1\76\60\0\1\77\60\0\1\100"+
    "\60\0\1\101\60\0\1\102\66\0\1\103\11\0\6\47"+
    "\1\0\1\104\51\47\1\0\3\2\5\0\2\2\1\105"+
    "\1\2\1\0\3\2\1\0\15\2\23\0\3\2\5\0"+
    "\4\2\1\106\1\107\2\2\1\0\15\2\23\0\3\2"+
    "\5\0\4\2\1\0\3\2\1\0\2\2\1\110\12\2"+
    "\52\0\1\111\31\0\3\2\5\0\4\2\1\0\3\2"+
    "\1\0\6\2\1\112\6\2\23\0\3\2\5\0\4\2"+
    "\1\0\2\2\1\113\1\0\15\2\51\0\1\114\62\0"+
    "\1\115\30\0\3\2\5\0\4\2\1\0\3\2\1\0"+
    "\5\2\1\116\7\2\23\0\3\2\5\0\4\2\1\0"+
    "\3\2\1\0\7\2\1\117\5\2\23\0\3\2\5\0"+
    "\4\2\1\120\1\121\2\2\1\0\15\2\55\0\1\122"+
    "\26\0\3\2\5\0\4\2\1\0\3\2\1\0\11\2"+
    "\1\123\3\2\23\0\3\2\5\0\4\2\1\124\1\125"+
    "\2\2\1\0\15\2\23\0\3\2\5\0\4\2\1\0"+
    "\3\2\1\0\14\2\1\126\23\0\3\2\5\0\1\2"+
    "\1\127\2\2\1\0\3\2\1\0\15\2\23\0\3\2"+
    "\5\0\4\2\1\130\1\131\2\2\1\0\15\2\23\0"+
    "\3\2\5\0\4\2\1\0\3\2\1\0\6\2\1\132"+
    "\6\2\23\0\3\2\5\0\3\2\1\133\1\0\3\2"+
    "\1\0\15\2\23\0\3\2\5\0\3\2\1\134\1\0"+
    "\3\2\1\0\15\2\51\0\1\135\32\0\3\2\5\0"+
    "\4\2\1\0\3\2\1\0\5\2\1\136\7\2\23\0"+
    "\3\2\5\0\3\2\1\137\1\0\3\2\1\0\15\2"+
    "\23\0\3\2\5\0\4\2\1\0\3\2\1\140\1\141"+
    "\14\2\46\0\1\142\51\0\2\143\43\0\3\2\5\0"+
    "\4\2\1\0\3\2\1\0\2\2\1\144\12\2\23\0"+
    "\3\2\5\0\4\2\1\143\1\145\2\2\1\0\15\2"+
    "\47\0\1\146\34\0\3\2\5\0\4\2\1\0\3\2"+
    "\1\0\3\2\1\147\11\2\51\0\1\150\32\0\3\2"+
    "\5\0\4\2\1\0\3\2\1\0\5\2\1\151\7\2"+
    "\51\0\1\152\32\0\3\2\5\0\4\2\1\0\3\2"+
    "\1\0\5\2\1\153\7\2\23\0\3\2\5\0\4\2"+
    "\1\0\3\2\1\0\11\2\1\154\3\2\43\0\2\155"+
    "\37\0\3\2\5\0\4\2\1\0\3\2\1\155\1\156"+
    "\14\2\23\0\3\2\5\0\1\2\1\157\2\2\1\0"+
    "\3\2\1\0\15\2\23\0\3\2\5\0\4\2\1\0"+
    "\3\2\1\160\1\161\14\2\23\0\3\2\5\0\4\2"+
    "\1\162\1\163\2\2\1\0\15\2\52\0\1\164\31\0"+
    "\3\2\5\0\4\2\1\0\3\2\1\0\6\2\1\165"+
    "\6\2\23\0\3\2\5\0\4\2\1\0\3\2\1\0"+
    "\11\2\1\166\3\2\43\0\2\167\37\0\3\2\5\0"+
    "\4\2\1\0\3\2\1\167\1\170\14\2\51\0\1\171"+
    "\32\0\3\2\5\0\4\2\1\0\3\2\1\0\5\2"+
    "\1\172\7\2\52\0\1\173\31\0\3\2\5\0\4\2"+
    "\1\0\3\2\1\0\6\2\1\174\6\2\23\0\3\2"+
    "\5\0\4\2\1\0\3\2\1\0\7\2\1\175\5\2"+
    "\55\0\1\176\26\0\3\2\5\0\4\2\1\0\3\2"+
    "\1\0\11\2\1\177\3\2\41\0\1\200\42\0\3\2"+
    "\5\0\4\2\1\0\1\2\1\201\1\2\1\0\15\2"+
    "\37\0\2\202\2\0\2\203\37\0\3\2\5\0\4\2"+
    "\1\202\1\204\2\2\1\203\1\205\14\2\23\0\3\2"+
    "\5\0\4\2\1\0\2\2\1\206\1\0\15\2\54\0"+
    "\1\207\27\0\3\2\5\0\4\2\1\0\3\2\1\0"+
    "\10\2\1\210\4\2\53\0\1\211\30\0\3\2\5\0"+
    "\4\2\1\0\3\2\1\0\7\2\1\212\5\2\23\0"+
    "\3\2\5\0\4\2\1\0\3\2\1\0\5\2\1\213"+
    "\7\2\51\0\1\214\61\0\1\215\31\0\3\2\5\0"+
    "\4\2\1\0\3\2\1\0\5\2\1\216\7\2\23\0"+
    "\3\2\5\0\4\2\1\0\3\2\1\0\6\2\1\217"+
    "\6\2\23\0\3\2\5\0\4\2\1\0\3\2\1\0"+
    "\5\2\1\220\7\2\42\0\1\221\41\0\3\2\5\0"+
    "\4\2\1\0\2\2\1\222\1\0\15\2\52\0\1\223"+
    "\61\0\1\224\30\0\3\2\5\0\4\2\1\0\3\2"+
    "\1\0\6\2\1\225\6\2\23\0\3\2\5\0\4\2"+
    "\1\0\3\2\1\0\7\2\1\226\5\2\43\0\2\227"+
    "\37\0\3\2\5\0\4\2\1\0\3\2\1\227\1\230"+
    "\14\2\22\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5096];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\1\1\11\1\0\3\1\1\0\2\1\1\0"+
    "\10\1\1\0\6\1\1\0\12\11\1\0\3\1\1\0"+
    "\3\1\1\0\3\1\1\0\7\1\12\11\1\1\1\0"+
    "\2\1\1\11\2\1\2\0\2\1\1\0\1\1\1\0"+
    "\1\1\1\0\3\1\1\0\4\1\1\0\2\1\1\0"+
    "\1\1\1\11\1\0\2\1\1\11\1\1\1\0\1\1"+
    "\1\11\2\1\1\11\2\1\1\0\1\1\1\0\1\1"+
    "\1\0\2\1\1\11\1\1\1\0\1\1\1\0\2\1"+
    "\1\11\1\1\1\11\1\1\2\0\3\1\1\11\1\1"+
    "\1\0\2\1\2\0\3\1\1\0\1\1\2\11\2\1"+
    "\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	private void error(String message)
	{
		System.err.println("Error at line " + (yyline+1) + ", column " + (yycolumn+1) + " : " + message);
	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalizadorLexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 226) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;           
    int totalRead = 0;
    while (totalRead < requested) {
      int numRead = zzReader.read(zzBuffer, zzEndRead + totalRead, requested - totalRead);
      if (numRead == -1) {
        break;
      }
      totalRead += numRead;
    }

    if (totalRead > 0) {
      zzEndRead += totalRead;
      if (totalRead == requested) { /* possibly more input available */
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      return false;
    }

    // totalRead = 0: End of stream
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { return new Symbol(sym.ID, yytext().intern());
          }
        case 49: break;
        case 2: 
          { return new Symbol(sym._INTEGER_, new Integer(yytext()));
          }
        case 50: break;
        case 3: 
          { /* ignore white space. */
          }
        case 51: break;
        case 4: 
          { return new Symbol(sym.DIV,yyline+1,yycolumn+1);
          }
        case 52: break;
        case 5: 
          { return new Symbol(sym.NOT, yyline+1, yycolumn+1);
          }
        case 53: break;
        case 6: 
          { return new Symbol(sym.ASSIGN, yyline+1, yycolumn+1);
          }
        case 54: break;
        case 7: 
          { return new Symbol(sym.LESS, yyline+1, yycolumn+1);
          }
        case 55: break;
        case 8: 
          { return new Symbol(sym.GREATER, yyline+1, yycolumn+1);
          }
        case 56: break;
        case 9: 
          { return new Symbol(sym.ADD,yyline+1,yycolumn+1);
          }
        case 57: break;
        case 10: 
          { return new Symbol(sym.SUB,yyline+1,yycolumn+1);
          }
        case 58: break;
        case 11: 
          { return new Symbol(sym.MULT,yyline+1,yycolumn+1);
          }
        case 59: break;
        case 12: 
          { return new Symbol(sym.DOT,yyline+1,yycolumn+1);
          }
        case 60: break;
        case 13: 
          { return new Symbol(sym.COMMA,yyline+1,yycolumn+1);
          }
        case 61: break;
        case 14: 
          { return new Symbol(sym.SEMI,yyline+1,yycolumn+1);
          }
        case 62: break;
        case 15: 
          { return new Symbol(sym.LBRACE,yyline+1,yycolumn+1);
          }
        case 63: break;
        case 16: 
          { return new Symbol(sym.RBRACE,yyline+1,yycolumn+1);
          }
        case 64: break;
        case 17: 
          { return new Symbol(sym.LPARENS,yyline+1,yycolumn+1);
          }
        case 65: break;
        case 18: 
          { return new Symbol(sym.RPARENS,yyline+1,yycolumn+1);
          }
        case 66: break;
        case 19: 
          { return new Symbol(sym.LBRACKET,yyline+1,yycolumn+1);
          }
        case 67: break;
        case 20: 
          { return new Symbol(sym.RBRACKET,yyline+1,yycolumn+1);
          }
        case 68: break;
        case 21: 
          { return new Symbol(sym.STRING_LITERAL, yyline+1, yycolumn+1, yytext());
          }
        case 69: break;
        case 22: 
          { return new Symbol(sym.IF,yyline+1,yycolumn+1);
          }
        case 70: break;
        case 23: 
          { return new Symbol(sym.NOT_EQUAL, yyline+1, yycolumn+1);
          }
        case 71: break;
        case 24: 
          { return new Symbol(sym.AND, yyline+1, yycolumn+1);
          }
        case 72: break;
        case 25: 
          { return new Symbol(sym.EQUAL, yyline+1, yycolumn+1);
          }
        case 73: break;
        case 26: 
          { return new Symbol(sym.LESS_OR_EQUAL, yyline+1, yycolumn+1);
          }
        case 74: break;
        case 27: 
          { return new Symbol(sym.GREATER_OR_EQUAL, yyline+1, yycolumn+1);
          }
        case 75: break;
        case 28: 
          { return new Symbol(sym.ADD_ASSIGN, yyline+1, yycolumn+1);
          }
        case 76: break;
        case 29: 
          { return new Symbol(sym.SUB_ASSIGN, yyline+1, yycolumn+1);
          }
        case 77: break;
        case 30: 
          { return new Symbol(sym.MULT_ASSIGN, yyline+1, yycolumn+1);
          }
        case 78: break;
        case 31: 
          { return new Symbol(sym.OR, yyline+1, yycolumn+1);
          }
        case 79: break;
        case 32: 
          { /* Ignore comment. */
          }
        case 80: break;
        case 33: 
          { return new Symbol(sym.INT,yyline+1,yycolumn+1);
          }
        case 81: break;
        case 34: 
          { return new Symbol(sym.NEW,yyline+1,yycolumn+1);
          }
        case 82: break;
        case 35: 
          { return new Symbol(sym.ELSE,yyline+1,yycolumn+1);
          }
        case 83: break;
        case 36: 
          { return new Symbol(sym.VOID,yyline+1,yycolumn+1);
          }
        case 84: break;
        case 37: 
          { return new Symbol(sym.MAIN,yyline+1,yycolumn+1);
          }
        case 85: break;
        case 38: 
          { return new Symbol(sym.TRUE,yyline+1,yycolumn+1);
          }
        case 86: break;
        case 39: 
          { return new Symbol(sym.THIS,yyline+1,yycolumn+1);
          }
        case 87: break;
        case 40: 
          { return new Symbol(sym.CLASS,yyline+1,yycolumn+1);
          }
        case 88: break;
        case 41: 
          { return new Symbol(sym.FALSE,yyline+1,yycolumn+1);
          }
        case 89: break;
        case 42: 
          { return new Symbol(sym.PUBLIC,yyline+1,yycolumn+1);
          }
        case 90: break;
        case 43: 
          { return new Symbol(sym.STRING,yyline+1,yycolumn+1);
          }
        case 91: break;
        case 44: 
          { return new Symbol(sym.RETURN,yyline+1,yycolumn+1);
          }
        case 92: break;
        case 45: 
          { return new Symbol(sym.BOOL,yyline+1,yycolumn+1);
          }
        case 93: break;
        case 46: 
          { return new Symbol(sym.PRINT_INT,yyline+1,yycolumn+1);
          }
        case 94: break;
        case 47: 
          { return new Symbol(sym.PRINT_STRING,yyline+1,yycolumn+1);
          }
        case 95: break;
        case 48: 
          { return new Symbol(sym.WHILE,yyline+1,yycolumn+1);
          }
        case 96: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
