
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140902 (SVN rev 60)
//----------------------------------------------------

package ar.edu.itba.geb.compiler.java.core;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RPARENS = 43;
  public static final int LPARENS = 42;
  public static final int STRING_LITERAL = 47;
  public static final int LBRACKET = 44;
  public static final int MULT = 35;
  public static final int GREATER_OR_EQUAL = 23;
  public static final int PRINT_INT = 13;
  public static final int NOT_EQUAL = 26;
  public static final int SEMI = 38;
  public static final int GREATER = 25;
  public static final int INT = 7;
  public static final int _INTEGER_ = 49;
  public static final int LESS = 24;
  public static final int FOR = 12;
  public static final int SUB_ASSIGN = 29;
  public static final int NOT = 32;
  public static final int AND = 20;
  public static final int _STRING_ = 48;
  public static final int LESS_OR_EQUAL = 22;
  public static final int OR = 31;
  public static final int COMMA = 37;
  public static final int BOOL = 8;
  public static final int CLASS = 2;
  public static final int DIV = 36;
  public static final int ASSIGN = 27;
  public static final int MAIN = 4;
  public static final int IF = 9;
  public static final int THIS = 17;
  public static final int ID = 46;
  public static final int DOT = 39;
  public static final int ADD_ASSIGN = 28;
  public static final int EOF = 0;
  public static final int RETURN = 6;
  public static final int RBRACKET = 45;
  public static final int EQUAL = 21;
  public static final int TRUE = 15;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int ADD = 33;
  public static final int VOID = 3;
  public static final int LBRACE = 40;
  public static final int ELSE = 10;
  public static final int WHILE = 11;
  public static final int PUBLIC = 19;
  public static final int RBRACE = 41;
  public static final int STRING = 5;
  public static final int FALSE = 16;
  public static final int MULT_ASSIGN = 30;
  public static final int SUB = 34;
  public static final int PRINT_STRING = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "VOID",
  "MAIN",
  "STRING",
  "RETURN",
  "INT",
  "BOOL",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "PRINT_INT",
  "PRINT_STRING",
  "TRUE",
  "FALSE",
  "THIS",
  "NEW",
  "PUBLIC",
  "AND",
  "EQUAL",
  "LESS_OR_EQUAL",
  "GREATER_OR_EQUAL",
  "LESS",
  "GREATER",
  "NOT_EQUAL",
  "ASSIGN",
  "ADD_ASSIGN",
  "SUB_ASSIGN",
  "MULT_ASSIGN",
  "OR",
  "NOT",
  "ADD",
  "SUB",
  "MULT",
  "DIV",
  "COMMA",
  "SEMI",
  "DOT",
  "LBRACE",
  "RBRACE",
  "LPARENS",
  "RPARENS",
  "LBRACKET",
  "RBRACKET",
  "ID",
  "STRING_LITERAL",
  "_STRING_",
  "_INTEGER_"
  };
}

